# Basic
title:              "Qasar Younis"
name:               "Qasar Younis"
description:        "My name is Qasar Younis - this is my homepage. I'm a founder, engineer, and angel investor."

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "https://qy.co"
author:             "Qasar Younis"
twitter:
  username:         "qasar"
#facebook:
#  app_id:           1234
#    publisher:      1234

# URL
#baseurl:            "https://rohanpai.github.io/website"
#baseurl:            "http://qasaryounis.com" #For Root Domain
permalink:          /essays/:title/

# Markdown
markdown:           kramdown

# Collections
collections:
  essay:
    output: true
    permalink: /writings/:name/

# Navigation
nav:
  - name:           "Books"
    href:           "books"
  - name:           "Writings"
    href:           "writings"
  - name:           "Photos"
    href:           "photos"
  - name:           "Links"
    href:           "links"
  - name:           "Press"
    href:           "press"
  - name:           "About"
    href:           "about"



# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "essay"
    values:
      layout:       "post"
      image:        "/assets/essay-previews/default.png"

plugins:
- jekyll-seo-tag
- jekyll-sitemap

# Include service worker file in build (GitHub Pages copies root files automatically)
include:
  - sw.js

future: true

